name: GPU02-V-1
channels:
  - defaults
dependencies:
  - _tflow_select=2.1.0=gpu
  - absl-py=0.9.0=py37_0
  - astor=0.8.0=py37_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - blinker=1.4=py37_0
  - brotlipy=0.7.0=py37he774522_1000
  - ca-certificates=2020.6.24=0
  - cachetools=4.1.0=py_1
  - certifi=2020.6.20=py37_0
  - cffi=1.14.0=py37h7a1dbc1_0
  - chardet=3.0.4=py37_1003
  - click=7.1.2=py_0
  - cloudpickle=1.5.0=py_0
  - colorama=0.4.3=py_0
  - cryptography=2.9.2=py37h7a1dbc1_0
  - cudatoolkit=10.1.243=h74a9793_0
  - cudnn=7.6.5=cuda10.1_0
  - decorator=4.4.2=py_0
  - entrypoints=0.3=py37_0
  - git=2.23.0=h6bb4b03_0
  - google-auth=1.14.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - grpcio=1.27.2=py37h351948d_0
  - h5py=2.10.0=py37h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - idna=2.10=py_0
  - intel-openmp=2020.1=216
  - ipykernel=5.3.0=py37h5ca1d4c_0
  - ipython=7.16.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.17.1=py37_0
  - jupyter_client=6.1.5=py_0
  - jupyter_core=4.6.3=py37_0
  - keras-applications=1.0.8=py_0
  - libprotobuf=3.12.3=h7bd577a_0
  - libsodium=1.0.18=h62dcd97_0
  - markdown=3.1.1=py37_0
  - mkl=2020.1=216
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.1.0=py37h45dec08_0
  - mkl_random=1.1.1=py37h47e9c7a_0
  - numpy-base=1.18.5=py37hc3f5095_0
  - oauthlib=3.1.0=py_0
  - openssl=1.1.1g=he774522_0
  - opt_einsum=3.1.0=py_0
  - pandas=1.0.5=py37h47e9c7a_0
  - parso=0.7.0=py_0
  - pickleshare=0.7.5=py37_0
  - pip=20.1.1=py37_1
  - prompt-toolkit=3.0.5=py_0
  - protobuf=3.12.3=py37h33f27b4_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_0
  - pygments=2.6.1=py_0
  - pyjwt=1.7.1=py37_0
  - pyopenssl=19.1.0=py37_0
  - pyreadline=2.1=py37_1
  - pysocks=1.7.1=py37_0
  - python=3.7.7=h81c818b_4
  - python-dateutil=2.8.1=py_0
  - pytz=2020.1=py_0
  - pywin32=227=py37he774522_1
  - pyzmq=19.0.1=py37ha925a31_1
  - requests=2.24.0=py_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.0=py_0
  - setuptools=47.3.1=py37_0
  - six=1.15.0=py_0
  - spyder-kernels=1.9.1=py37_0
  - sqlite=3.32.3=h2a8f88b_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow-base=2.1.0=gpu_py37h55f5790_0
  - tensorflow-estimator=2.1.0=pyhd54b08b_0
  - termcolor=1.1.0=py37_1
  - tornado=6.0.4=py37he774522_1
  - traitlets=4.3.3=py37_0
  - urllib3=1.25.9=py_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wcwidth=0.2.5=py_0
  - werkzeug=0.16.1=py_0
  - wheel=0.34.2=py37_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_0
  - wrapt=1.12.1=py37he774522_1
  - zeromq=4.3.2=ha925a31_2
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - astunparse==1.6.3
    - comtypes==1.1.7
    - contextlib2==0.6.0.post1
    - cycler==0.10.0
    - cython==0.29.21
    - d3dshot==0.1.5
    - gast==0.3.3
    - gviz-api==1.9.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.2.0
    - lxml==4.5.1
    - matplotlib==3.2.2
    - mss==6.0.0
    - numpy==1.18.5
    - opencv-python==4.3.0.36
    - pillow==7.1.2
    - pycocotools==2.0
    - pynput==1.6.8
    - pyparsing==2.4.7
    - pyvjoy==1.0.1
    - scipy==1.4.1
    - tensorboard==2.2.2
    - tensorboard-plugin-profile==2.2.0
    - tensorflow==2.3.0
    - tensorflow-gpu==2.3.0
    - tensorflow-gpu-estimator==2.2.0
    - tf-slim==1.1.0
prefix: C:\Users\Preetham\Anaconda3\envs\GPU02-V-1
